string_classification_table = {
    'id': ['id', 'uuid'],
    'name': ['name', 'user', 'username', 'contributor', 'artists'],
    'description': ['description', 'summary', 'text', 'title', 'comment', 'value', 'content', 'message'],
    'time_zone': ['time_zone'],
    'area': ['area'],
    'location': ['location', 'country', 'address'],
    'region': ['region'],
    'url': ['url', 'uri', 'link', 'href', 'website'],
    'language': ['language'],
    'media_type': ['media_type', 'mime_type'],
    'color': ['color'],
    'email': ['email'],
    'query': ['query', 'q', 'search'],
    'path': ['path'],
    'domain': ['domain'],
    'token': ['token', 'code', 'key'],
    'category': ['category', 'type', 'genre', 'kind', 'tag', 'output'],
    'ip': ['ip', 'host'],
    'string_datetime': ['datetime', 'since', 'until', 'after', 'before', 'time', 'before', 'after', 'min'],
    'string_date': ['date', 'due']
}
